// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lab.proto

package com.example.labo.grpc;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laboratory.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Utilise Long en Java
   * </pre>
   *
   * <code>int64 request_id = 1;</code>
   * @return The requestId.
   */
  long getRequestId();
}
