// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lab.proto

package com.example.labo.grpc;

public final class Lab {
  private Lab() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laboratory_SubmitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_laboratory_SubmitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laboratory_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_laboratory_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laboratory_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_laboratory_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_laboratory_TestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_laboratory_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tLab.proto\022\nlaboratory\"8\n\rSubmitRequest" +
      "\022\024\n\014patient_name\030\001 \001(\t\022\021\n\ttest_type\030\002 \001(" +
      "\t\" \n\nGetRequest\022\022\n\nrequest_id\030\001 \001(\003\"O\n\rU" +
      "pdateRequest\022\022\n\nrequest_id\030\001 \001(\003\022\022\n\nnew_" +
      "status\030\002 \001(\t\022\026\n\016result_details\030\003 \001(\t\"s\n\014" +
      "TestResponse\022\022\n\nrequest_id\030\001 \001(\003\022\024\n\014pati" +
      "ent_name\030\002 \001(\t\022\021\n\ttest_type\030\003 \001(\t\022\016\n\006sta" +
      "tus\030\004 \001(\t\022\026\n\016result_details\030\005 \001(\t2\350\001\n\nLa" +
      "bService\022J\n\021SubmitTestRequest\022\031.laborato" +
      "ry.SubmitRequest\032\030.laboratory.TestRespon" +
      "se\"\000\022C\n\rGetTestResult\022\026.laboratory.GetRe" +
      "quest\032\030.laboratory.TestResponse\"\000\022I\n\020Upd" +
      "ateTestStatus\022\031.laboratory.UpdateRequest" +
      "\032\030.laboratory.TestResponse\"\000B\031\n\025com.exam" +
      "ple.labo.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_laboratory_SubmitRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_laboratory_SubmitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_laboratory_SubmitRequest_descriptor,
        new java.lang.String[] { "PatientName", "TestType", });
    internal_static_laboratory_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_laboratory_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_laboratory_GetRequest_descriptor,
        new java.lang.String[] { "RequestId", });
    internal_static_laboratory_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_laboratory_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_laboratory_UpdateRequest_descriptor,
        new java.lang.String[] { "RequestId", "NewStatus", "ResultDetails", });
    internal_static_laboratory_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_laboratory_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_laboratory_TestResponse_descriptor,
        new java.lang.String[] { "RequestId", "PatientName", "TestType", "Status", "ResultDetails", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
