// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lab.proto

package com.example.labo.grpc;

public interface SubmitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laboratory.SubmitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patient_name = 1;</code>
   * @return The patientName.
   */
  java.lang.String getPatientName();
  /**
   * <code>string patient_name = 1;</code>
   * @return The bytes for patientName.
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>string test_type = 2;</code>
   * @return The testType.
   */
  java.lang.String getTestType();
  /**
   * <code>string test_type = 2;</code>
   * @return The bytes for testType.
   */
  com.google.protobuf.ByteString
      getTestTypeBytes();
}
