// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lab.proto

package com.example.labo.grpc;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laboratory.TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 request_id = 1;</code>
   * @return The requestId.
   */
  long getRequestId();

  /**
   * <code>string patient_name = 2;</code>
   * @return The patientName.
   */
  java.lang.String getPatientName();
  /**
   * <code>string patient_name = 2;</code>
   * @return The bytes for patientName.
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>string test_type = 3;</code>
   * @return The testType.
   */
  java.lang.String getTestType();
  /**
   * <code>string test_type = 3;</code>
   * @return The bytes for testType.
   */
  com.google.protobuf.ByteString
      getTestTypeBytes();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * Ajout du résultat si COMPLETED
   * </pre>
   *
   * <code>string result_details = 5;</code>
   * @return The resultDetails.
   */
  java.lang.String getResultDetails();
  /**
   * <pre>
   * Ajout du résultat si COMPLETED
   * </pre>
   *
   * <code>string result_details = 5;</code>
   * @return The bytes for resultDetails.
   */
  com.google.protobuf.ByteString
      getResultDetailsBytes();
}
