// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lab.proto

package com.example.labo.grpc;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:laboratory.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 request_id = 1;</code>
   * @return The requestId.
   */
  long getRequestId();

  /**
   * <pre>
   * PENDING, IN_PROGRESS, COMPLETED
   * </pre>
   *
   * <code>string new_status = 2;</code>
   * @return The newStatus.
   */
  java.lang.String getNewStatus();
  /**
   * <pre>
   * PENDING, IN_PROGRESS, COMPLETED
   * </pre>
   *
   * <code>string new_status = 2;</code>
   * @return The bytes for newStatus.
   */
  com.google.protobuf.ByteString
      getNewStatusBytes();

  /**
   * <code>string result_details = 3;</code>
   * @return The resultDetails.
   */
  java.lang.String getResultDetails();
  /**
   * <code>string result_details = 3;</code>
   * @return The bytes for resultDetails.
   */
  com.google.protobuf.ByteString
      getResultDetailsBytes();
}
