// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lab.proto

package com.example.labo.grpc;

/**
 * <pre>
 * Message pour mettre à jour le statut
 * </pre>
 *
 * Protobuf type {@code laboratory.UpdateRequest}
 */
public  final class UpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:laboratory.UpdateRequest)
    UpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateRequest.newBuilder() to construct.
  private UpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateRequest() {
    newStatus_ = "";
    resultDetails_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            requestId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            newStatus_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            resultDetails_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.labo.grpc.Lab.internal_static_laboratory_UpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.labo.grpc.Lab.internal_static_laboratory_UpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.labo.grpc.UpdateRequest.class, com.example.labo.grpc.UpdateRequest.Builder.class);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private long requestId_;
  /**
   * <code>int64 request_id = 1;</code>
   * @return The requestId.
   */
  public long getRequestId() {
    return requestId_;
  }

  public static final int NEW_STATUS_FIELD_NUMBER = 2;
  private volatile java.lang.Object newStatus_;
  /**
   * <pre>
   * PENDING, IN_PROGRESS, COMPLETED
   * </pre>
   *
   * <code>string new_status = 2;</code>
   * @return The newStatus.
   */
  public java.lang.String getNewStatus() {
    java.lang.Object ref = newStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newStatus_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * PENDING, IN_PROGRESS, COMPLETED
   * </pre>
   *
   * <code>string new_status = 2;</code>
   * @return The bytes for newStatus.
   */
  public com.google.protobuf.ByteString
      getNewStatusBytes() {
    java.lang.Object ref = newStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_DETAILS_FIELD_NUMBER = 3;
  private volatile java.lang.Object resultDetails_;
  /**
   * <code>string result_details = 3;</code>
   * @return The resultDetails.
   */
  public java.lang.String getResultDetails() {
    java.lang.Object ref = resultDetails_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultDetails_ = s;
      return s;
    }
  }
  /**
   * <code>string result_details = 3;</code>
   * @return The bytes for resultDetails.
   */
  public com.google.protobuf.ByteString
      getResultDetailsBytes() {
    java.lang.Object ref = resultDetails_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestId_ != 0L) {
      output.writeInt64(1, requestId_);
    }
    if (!getNewStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newStatus_);
    }
    if (!getResultDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resultDetails_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, requestId_);
    }
    if (!getNewStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newStatus_);
    }
    if (!getResultDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resultDetails_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.labo.grpc.UpdateRequest)) {
      return super.equals(obj);
    }
    com.example.labo.grpc.UpdateRequest other = (com.example.labo.grpc.UpdateRequest) obj;

    if (getRequestId()
        != other.getRequestId()) return false;
    if (!getNewStatus()
        .equals(other.getNewStatus())) return false;
    if (!getResultDetails()
        .equals(other.getResultDetails())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestId());
    hash = (37 * hash) + NEW_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getNewStatus().hashCode();
    hash = (37 * hash) + RESULT_DETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getResultDetails().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.labo.grpc.UpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.labo.grpc.UpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.labo.grpc.UpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.labo.grpc.UpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.labo.grpc.UpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message pour mettre à jour le statut
   * </pre>
   *
   * Protobuf type {@code laboratory.UpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:laboratory.UpdateRequest)
      com.example.labo.grpc.UpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.labo.grpc.Lab.internal_static_laboratory_UpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.labo.grpc.Lab.internal_static_laboratory_UpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.labo.grpc.UpdateRequest.class, com.example.labo.grpc.UpdateRequest.Builder.class);
    }

    // Construct using com.example.labo.grpc.UpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = 0L;

      newStatus_ = "";

      resultDetails_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.labo.grpc.Lab.internal_static_laboratory_UpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.example.labo.grpc.UpdateRequest getDefaultInstanceForType() {
      return com.example.labo.grpc.UpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.labo.grpc.UpdateRequest build() {
      com.example.labo.grpc.UpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.labo.grpc.UpdateRequest buildPartial() {
      com.example.labo.grpc.UpdateRequest result = new com.example.labo.grpc.UpdateRequest(this);
      result.requestId_ = requestId_;
      result.newStatus_ = newStatus_;
      result.resultDetails_ = resultDetails_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.labo.grpc.UpdateRequest) {
        return mergeFrom((com.example.labo.grpc.UpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.labo.grpc.UpdateRequest other) {
      if (other == com.example.labo.grpc.UpdateRequest.getDefaultInstance()) return this;
      if (other.getRequestId() != 0L) {
        setRequestId(other.getRequestId());
      }
      if (!other.getNewStatus().isEmpty()) {
        newStatus_ = other.newStatus_;
        onChanged();
      }
      if (!other.getResultDetails().isEmpty()) {
        resultDetails_ = other.resultDetails_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.labo.grpc.UpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.labo.grpc.UpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long requestId_ ;
    /**
     * <code>int64 request_id = 1;</code>
     * @return The requestId.
     */
    public long getRequestId() {
      return requestId_;
    }
    /**
     * <code>int64 request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(long value) {
      
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object newStatus_ = "";
    /**
     * <pre>
     * PENDING, IN_PROGRESS, COMPLETED
     * </pre>
     *
     * <code>string new_status = 2;</code>
     * @return The newStatus.
     */
    public java.lang.String getNewStatus() {
      java.lang.Object ref = newStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * PENDING, IN_PROGRESS, COMPLETED
     * </pre>
     *
     * <code>string new_status = 2;</code>
     * @return The bytes for newStatus.
     */
    public com.google.protobuf.ByteString
        getNewStatusBytes() {
      java.lang.Object ref = newStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * PENDING, IN_PROGRESS, COMPLETED
     * </pre>
     *
     * <code>string new_status = 2;</code>
     * @param value The newStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PENDING, IN_PROGRESS, COMPLETED
     * </pre>
     *
     * <code>string new_status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewStatus() {
      
      newStatus_ = getDefaultInstance().getNewStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PENDING, IN_PROGRESS, COMPLETED
     * </pre>
     *
     * <code>string new_status = 2;</code>
     * @param value The bytes for newStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newStatus_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object resultDetails_ = "";
    /**
     * <code>string result_details = 3;</code>
     * @return The resultDetails.
     */
    public java.lang.String getResultDetails() {
      java.lang.Object ref = resultDetails_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultDetails_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string result_details = 3;</code>
     * @return The bytes for resultDetails.
     */
    public com.google.protobuf.ByteString
        getResultDetailsBytes() {
      java.lang.Object ref = resultDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string result_details = 3;</code>
     * @param value The resultDetails to set.
     * @return This builder for chaining.
     */
    public Builder setResultDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resultDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string result_details = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultDetails() {
      
      resultDetails_ = getDefaultInstance().getResultDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string result_details = 3;</code>
     * @param value The bytes for resultDetails to set.
     * @return This builder for chaining.
     */
    public Builder setResultDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resultDetails_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:laboratory.UpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:laboratory.UpdateRequest)
  private static final com.example.labo.grpc.UpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.labo.grpc.UpdateRequest();
  }

  public static com.example.labo.grpc.UpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateRequest>() {
    @java.lang.Override
    public UpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.labo.grpc.UpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

